import { useState } from "react";
import { motion } from "framer-motion";
import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, HeadingLevel, TextRun } from "docx";
import { saveAs } from "file-saver";
import { FileDown, FileText, FileType, Copy, Check, Clock, BookMarked, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const sections = [
  { key: "abstract",            label: "Abstract",          color: "#6366f1", icon: "📑" },
  { key: "literature_review",   label: "Literature Review", color: "#a78bfa", icon: "📚" },
  { key: "research_gaps",       label: "Research Gaps",     color: "#f87171", icon: "⚠️" },
  { key: "proposed_future_work",label: "Future Work",       color: "#34d399", icon: "🚀" },
  { key: "conclusion",          label: "Conclusion",        color: "#38bdf8", icon: "🎯" },
];

export default function ReportCard({ data }) {
  const [copied, setCopied] = useState(false);
  const [activeNav, setActiveNav] = useState(null);

  if (!data) return null;

  const reportText = `# Generated Research Report\n\n## Abstract\n${data.abstract || ""}\n\n## Literature Review\n${data.literature_review || ""}\n\n## Research Gaps\n${data.research_gaps || ""}\n\n## Future Work\n${data.proposed_future_work || ""}\n\n## Conclusion\n${data.conclusion || ""}`;

  // Word count & read time
  const wordCount = reportText.split(/\s+/).filter(Boolean).length;
  const readTime = Math.max(1, Math.ceil(wordCount / 200));

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadMarkdown = () => {
    saveAs(new Blob([reportText], { type: "text/markdown;charset=utf-8" }), "Research_Report.md");
  };

  const downloadPDF = () => {
    const doc = new jsPDF({
      unit: "pt",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;
    let yPos = 50;

    // Header title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59);
    doc.text("AI Research Analysis Report", margin, yPos);

    yPos += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by ResearchPilot AI · ${new Date().toLocaleDateString()} · ~${readTime} min read`, margin, yPos);

    yPos += 14;
    doc.setDrawColor(203, 213, 225);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 24;

    const printSection = (title, content) => {
      if (!content) return;
      if (yPos > doc.internal.pageSize.getHeight() - 80) {
        doc.addPage();
        yPos = 50;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(49, 46, 129);
      doc.text(title, margin, yPos);
      yPos += 16;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);
      const splitText = doc.splitTextToSize(content, contentWidth);

      for (let i = 0; i < splitText.length; i++) {
        if (yPos > doc.internal.pageSize.getHeight() - 50) {
          doc.addPage();
          yPos = 50;
        }
        doc.text(splitText[i], margin, yPos);
        yPos += 14;
      }
      yPos += 18;
    };

    printSection("1. Abstract", data.abstract);
    printSection("2. Literature Review", data.literature_review);
    printSection("3. Research Gaps", data.research_gaps);
    printSection("4. Proposed Future Work", data.proposed_future_work);
    printSection("5. Conclusion", data.conclusion);

    // Page numbering
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${totalPages} · ResearchPilot AI`, pageWidth / 2, doc.internal.pageSize.getHeight() - 20, { align: "center" });
    }

    doc.save("Research_Report.pdf");
  };

  const downloadDOCX = async () => {
    const doc = new Document({
      sections: [{
        children: [
          new Paragraph({ text: "AI Research Analysis Report", heading: HeadingLevel.TITLE }),
          new Paragraph({
            children: [
              new TextRun({ text: `Generated by ResearchPilot AI on ${new Date().toLocaleDateString()}`, italics: true, color: "666666" }),
            ],
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "Abstract", heading: HeadingLevel.HEADING_1 }),
          new Paragraph(data.abstract ?? ""),
          new Paragraph({ text: "Literature Review", heading: HeadingLevel.HEADING_1 }),
          new Paragraph(data.literature_review ?? ""),
          new Paragraph({ text: "Research Gaps", heading: HeadingLevel.HEADING_1 }),
          new Paragraph(data.research_gaps ?? ""),
          new Paragraph({ text: "Proposed Future Work", heading: HeadingLevel.HEADING_1 }),
          new Paragraph(data.proposed_future_work ?? ""),
          new Paragraph({ text: "Conclusion", heading: HeadingLevel.HEADING_1 }),
          new Paragraph(data.conclusion ?? ""),
        ],
      }],
    });
    saveAs(await Packer.toBlob(doc), "Research_Report.docx");
  };

  const scrollToSection = (key) => {
    setActiveNav(key);
    const element = document.getElementById(`report-section-${key}`);
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  const downloads = [
    { label: "Copy Text", icon: copied ? Check : Copy, color: copied ? "#34d399" : "#cbd5e1", bg: "rgba(30,41,59,0.7)", border: copied ? "rgba(52,211,153,0.3)" : "rgba(99,102,241,0.2)", fn: handleCopy },
    { label: "Markdown", icon: FileText, color: "#94a3b8", bg: "rgba(148,163,184,0.1)", border: "rgba(148,163,184,0.2)", fn: downloadMarkdown },
    { label: "PDF Export", icon: FileType, color: "#f87171", bg: "rgba(248,113,113,0.1)", border: "rgba(248,113,113,0.25)", fn: downloadPDF },
    { label: "DOCX Document", icon: FileDown, color: "#60a5fa", bg: "rgba(96,165,250,0.1)", border: "rgba(96,165,250,0.25)", fn: downloadDOCX },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-4"
    >
      {/* Report header */}
      <div
        className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5 rounded-2xl p-6 shadow-xl"
        style={{
          background: "linear-gradient(135deg,rgba(99,102,241,0.18),rgba(167,139,250,0.08))",
          border: "1px solid rgba(99,102,241,0.25)",
        }}
      >
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-semibold text-indigo-400 bg-indigo-500/10 border border-indigo-500/20">
              <Sparkles size={11} /> Comprehensive Synthesis
            </span>
            <span className="inline-flex items-center gap-1 text-xs text-slate-400">
              <Clock size={11} /> ~{readTime} min read · {wordCount} words
            </span>
          </div>
          <h2 className="text-xl font-bold text-white tracking-tight">
            Executive Research Synthesis Report
          </h2>
          <p className="text-xs text-slate-400">
            Formulated across multi-agent consensus by ResearchPilot AI
          </p>
        </div>

        {/* Download & action buttons */}
        <div className="flex flex-wrap gap-2 flex-shrink-0">
          {downloads.map(({ label, icon: Icon, color, bg, border, fn }) => (
            <motion.button
              key={label}
              whileHover={{ scale: 1.04, y: -1 }}
              whileTap={{ scale: 0.96 }}
              onClick={fn}
              className="flex items-center gap-1.5 rounded-xl px-3.5 py-2 text-xs font-semibold transition shadow-sm"
              style={{ background: bg, border: `1px solid ${border}`, color }}
            >
              <Icon size={13} />
              {label}
            </motion.button>
          ))}
        </div>
      </div>

      {/* Quick Jump Navigator */}
      <div
        className="flex items-center gap-2 overflow-x-auto p-2 rounded-xl"
        style={{ background: "rgba(15,23,42,0.5)", border: "1px solid rgba(99,102,241,0.12)" }}
      >
        <span className="text-xs font-semibold text-slate-500 px-2 flex items-center gap-1 flex-shrink-0">
          <BookMarked size={12} /> Sections:
        </span>
        {sections.map(({ key, label, icon }) => (
          <button
            key={key}
            onClick={() => scrollToSection(key)}
            className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium whitespace-nowrap transition-all ${
              activeNav === key
                ? "bg-indigo-600/30 text-indigo-300 border border-indigo-500/40"
                : "text-slate-400 hover:text-white hover:bg-slate-800/60"
            }`}
          >
            <span>{icon}</span>
            <span>{label}</span>
          </button>
        ))}
      </div>

      {/* Report sections */}
      <div className="space-y-4">
        {sections.map(({ key, label, color, icon }, i) => {
          const content = data[key];
          if (!content) return null;
          return (
            <motion.div
              id={`report-section-${key}`}
              key={key}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07, duration: 0.35 }}
              className="rounded-2xl overflow-hidden shadow-lg"
              style={{
                background: "rgba(15,23,42,0.65)",
                backdropFilter: "blur(20px)",
                border: "1px solid rgba(99,102,241,0.12)",
              }}
            >
              {/* Section header */}
              <div
                className="flex items-center justify-between px-6 py-3.5"
                style={{
                  borderBottom: `1px solid ${color}22`,
                  background: `${color}0c`,
                }}
              >
                <div className="flex items-center gap-3">
                  <span className="text-base">{icon}</span>
                  <h3 className="text-sm font-bold tracking-wide" style={{ color }}>
                    {label}
                  </h3>
                </div>
                <span className="text-[11px] text-slate-500 font-mono">
                  SECTION {i + 1}
                </span>
              </div>

              {/* Section content */}
              <div className="px-6 py-5 prose-dark leading-relaxed">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {content}
                </ReactMarkdown>
              </div>
            </motion.div>
          );
        })}
      </div>
    </motion.div>
  );
}